from models.reinforce import train_reinforce_model
from models.value_function_approximation import train_value_function_approximation_model

# train_value_function_approximation_model()
train_reinforce_model()
